version: '3.3'

services:
  database:
    image: postgres:latest
    container_name: postgres-mexafood-project
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
    external: true